/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package FinanceManager;

/**
 *
 * @author charl
 */
public class FinanceManagerPanel extends javax.swing.JFrame {

    /**
     * Creates new form FinanceManagerPanel
     */
    
    public FinanceManagerPanel() {
        initComponents();
        
        // Dummy summary data
        int totalPO = 12;
        double totalPayment = 4500.00;
        int pendingPO = 3;
        
        // Update labels
        displayTotalPO.setText(String.valueOf(totalPO));
        displayTotalPayment.setText("RM " + String.format("%.2f", totalPayment));
        displayPending.setText(String.valueOf(pendingPO));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MainPanel = new javax.swing.JPanel();
        maincontentPanel = new javax.swing.JPanel();
        sidebarPanel = new javax.swing.JPanel();
        btnManagePurchaseOrder = new javax.swing.JButton();
        btnVerifyInventoryUpdates = new javax.swing.JButton();
        btnProcessPayment = new javax.swing.JButton();
        btnGenerateReports = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnManagePurchaseOrder1 = new javax.swing.JButton();
        labelWelcome = new javax.swing.JLabel();
        labelRole = new javax.swing.JLabel();
        summaryPanel = new javax.swing.JPanel();
        labelFinancialSummary = new javax.swing.JLabel();
        labelTotalPO = new javax.swing.JLabel();
        labelTotalPayment = new javax.swing.JLabel();
        labelPending = new javax.swing.JLabel();
        displayTotalPO = new javax.swing.JLabel();
        displayTotalPayment = new javax.swing.JLabel();
        displayPending = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        MainPanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        MainPanel.setLayout(new java.awt.BorderLayout());

        maincontentPanel.setBackground(new java.awt.Color(255, 253, 236));
        maincontentPanel.setMaximumSize(new java.awt.Dimension(800, 600));
        maincontentPanel.setMinimumSize(new java.awt.Dimension(800, 600));
        maincontentPanel.setLayout(null);

        sidebarPanel.setBackground(new java.awt.Color(134, 167, 136));

        btnManagePurchaseOrder.setText("✅ Manage Purchase Order");
        btnManagePurchaseOrder.setMaximumSize(null);
        btnManagePurchaseOrder.setPreferredSize(null);
        btnManagePurchaseOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnManagePurchaseOrderMouseClicked(evt);
            }
        });
        btnManagePurchaseOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePurchaseOrderActionPerformed(evt);
            }
        });

        btnVerifyInventoryUpdates.setText("📊 Verify Inventory Updates");
        btnVerifyInventoryUpdates.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerifyInventoryUpdatesActionPerformed(evt);
            }
        });

        btnProcessPayment.setText("💵 Process Payments");
        btnProcessPayment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcessPaymentActionPerformed(evt);
            }
        });

        btnGenerateReports.setText("📁 Generate Reports");
        btnGenerateReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGenerateReportsActionPerformed(evt);
            }
        });

        btnLogout.setText("🔒 Logout");
        btnLogout.setToolTipText("");
        btnLogout.setPreferredSize(null);
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnManagePurchaseOrder1.setText("🛒 View Product Requisition");
        btnManagePurchaseOrder1.setPreferredSize(null);
        btnManagePurchaseOrder1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManagePurchaseOrder1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout sidebarPanelLayout = new javax.swing.GroupLayout(sidebarPanel);
        sidebarPanel.setLayout(sidebarPanelLayout);
        sidebarPanelLayout.setHorizontalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnGenerateReports, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnProcessPayment, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnVerifyInventoryUpdates, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePurchaseOrder1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnManagePurchaseOrder, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        sidebarPanelLayout.setVerticalGroup(
            sidebarPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(sidebarPanelLayout.createSequentialGroup()
                .addGap(81, 81, 81)
                .addComponent(btnManagePurchaseOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnManagePurchaseOrder1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnVerifyInventoryUpdates, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnProcessPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(btnGenerateReports, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(145, Short.MAX_VALUE))
        );

        maincontentPanel.add(sidebarPanel);
        sidebarPanel.setBounds(0, 0, 220, 618);

        labelWelcome.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        labelWelcome.setText("Welcome back!");
        maincontentPanel.add(labelWelcome);
        labelWelcome.setBounds(250, 90, 280, 40);

        labelRole.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        labelRole.setForeground(new java.awt.Color(102, 102, 102));
        labelRole.setText("Finance Manager");
        maincontentPanel.add(labelRole);
        labelRole.setBounds(250, 130, 110, 20);

        summaryPanel.setBackground(new java.awt.Color(255, 226, 226));

        labelFinancialSummary.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        labelFinancialSummary.setText("Financial Summary");

        labelTotalPO.setText("Total Purchase Orders:");

        labelTotalPayment.setText("Total Payments:");

        labelPending.setText("Pending Approvals:");

        javax.swing.GroupLayout summaryPanelLayout = new javax.swing.GroupLayout(summaryPanel);
        summaryPanel.setLayout(summaryPanelLayout);
        summaryPanelLayout.setHorizontalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addComponent(labelFinancialSummary, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, summaryPanelLayout.createSequentialGroup()
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(summaryPanelLayout.createSequentialGroup()
                                .addComponent(labelPending, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayPending, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(summaryPanelLayout.createSequentialGroup()
                                .addComponent(labelTotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(displayTotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(summaryPanelLayout.createSequentialGroup()
                                .addComponent(labelTotalPO, javax.swing.GroupLayout.DEFAULT_SIZE, 129, Short.MAX_VALUE)
                                .addGap(154, 154, 154)
                                .addComponent(displayTotalPO, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(15, 15, 15))))
        );
        summaryPanelLayout.setVerticalGroup(
            summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(summaryPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(labelFinancialSummary)
                .addGap(32, 32, 32)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(summaryPanelLayout.createSequentialGroup()
                        .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(displayTotalPO, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelTotalPO))
                        .addGap(42, 42, 42)
                        .addComponent(labelTotalPayment))
                    .addComponent(displayTotalPayment, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(summaryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelPending, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(displayPending, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        maincontentPanel.add(summaryPanel);
        summaryPanel.setBounds(270, 220, 390, 240);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        maincontentPanel.add(jLabel1);
        jLabel1.setBounds(770, 0, 20, 40);

        MainPanel.add(maincontentPanel, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 810, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(810, 610));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnGenerateReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGenerateReportsActionPerformed
        // TODO add your handling code here:
        this.dispose();
        FinancialReport financialReport = new FinancialReport();
        financialReport.setVisible(true);
    }//GEN-LAST:event_btnGenerateReportsActionPerformed

    private void btnProcessPaymentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcessPaymentActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ProcessPaymentPanel processpanel = new ProcessPaymentPanel();
        processpanel.setVisible(true);
    }//GEN-LAST:event_btnProcessPaymentActionPerformed

    private void btnVerifyInventoryUpdatesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerifyInventoryUpdatesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnVerifyInventoryUpdatesActionPerformed

    private void btnManagePurchaseOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePurchaseOrderActionPerformed
        // TODO add your handling code here:
        this.dispose();
        ManagePO managePO = new ManagePO();
        managePO.setVisible(true);
    }//GEN-LAST:event_btnManagePurchaseOrderActionPerformed

    private void btnManagePurchaseOrder1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManagePurchaseOrder1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagePurchaseOrder1ActionPerformed

    private void btnManagePurchaseOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnManagePurchaseOrderMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnManagePurchaseOrderMouseClicked

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel MainPanel;
    private javax.swing.JButton btnGenerateReports;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManagePurchaseOrder;
    private javax.swing.JButton btnManagePurchaseOrder1;
    private javax.swing.JButton btnProcessPayment;
    private javax.swing.JButton btnVerifyInventoryUpdates;
    private javax.swing.JLabel displayPending;
    private javax.swing.JLabel displayTotalPO;
    private javax.swing.JLabel displayTotalPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelFinancialSummary;
    private javax.swing.JLabel labelPending;
    private javax.swing.JLabel labelRole;
    private javax.swing.JLabel labelTotalPO;
    private javax.swing.JLabel labelTotalPayment;
    private javax.swing.JLabel labelWelcome;
    private javax.swing.JPanel maincontentPanel;
    private javax.swing.JPanel sidebarPanel;
    private javax.swing.JPanel summaryPanel;
    // End of variables declaration//GEN-END:variables
}
