/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Admin;

import java.awt.Color;
import javax.swing.JFrame;
import javax.swing.JOptionPane;


/**
 *
 * @author ELYSHA SOPHIA
 */
public class AdminTest extends javax.swing.JFrame {
    
    private String employeeID;
    private String position;

    Color DefaultColor,ClickedColor;
    
    public AdminTest(String identifier) {
        initComponents();
        // Safely split the identifier
        String[] parts = identifier.split(":");
        if (parts.length == 2) {
            this.employeeID = parts[0];
            this.position = parts[1];
        } else {
            this.employeeID = "Unknown";
            this.position = "Unknown";
            System.out.println("Error: LoggedInIdentifier has an unexpected format: [" + identifier + "]");
        }

        System.out.println("EmployeeID: " + employeeID);
        System.out.println("Position: " + position);
       
        
        DefaultColor=new Color(255,204,102);
        ClickedColor=new Color(255,204,51);
        
        //Set default color to pan on run time
        Menu01.setBackground(DefaultColor);
        Menu02.setBackground(DefaultColor);
        Menu03.setBackground(DefaultColor);
        Menu04.setBackground(DefaultColor);
        Menu06.setBackground(DefaultColor);
        Menu05.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        MenuName = new javax.swing.JLabel();
        Menu01 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        Menu02 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        Menu03 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        Menu04 = new javax.swing.JPanel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        Menu05 = new javax.swing.JPanel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Menu06 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        Menu07 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        Menu08 = new javax.swing.JPanel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jDesktopPanel = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(204, 221, 204));
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 221, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(89, 116, 69));

        MenuName.setFont(new java.awt.Font("Bookman Old Style", 1, 14)); // NOI18N
        MenuName.setForeground(new java.awt.Color(231, 240, 220));

        Menu01.setBackground(new java.awt.Color(255, 204, 102));
        Menu01.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu01.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu01MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu01MousePressed(evt);
            }
        });

        jLabel21.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(32, 52, 15));
        jLabel21.setText("Employee Management");

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-employee-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu01Layout = new javax.swing.GroupLayout(Menu01);
        Menu01.setLayout(Menu01Layout);
        Menu01Layout.setHorizontalGroup(
            Menu01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu01Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel21)
                .addContainerGap())
        );
        Menu01Layout.setVerticalGroup(
            Menu01Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel30, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(Menu01Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel21))
        );

        Menu02.setBackground(new java.awt.Color(255, 204, 102));
        Menu02.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu02.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu02MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu02MousePressed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(32, 52, 15));
        jLabel18.setText("Items Management");

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-items-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu02Layout = new javax.swing.GroupLayout(Menu02);
        Menu02.setLayout(Menu02Layout);
        Menu02Layout.setHorizontalGroup(
            Menu02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel18)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu02Layout.setVerticalGroup(
            Menu02Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel19)
            .addGroup(Menu02Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel18))
        );

        Menu03.setBackground(new java.awt.Color(255, 204, 102));
        Menu03.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu03.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu03MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu03MousePressed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(32, 52, 15));
        jLabel22.setText("Supplier Management");

        jLabel23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-supplier-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu03Layout = new javax.swing.GroupLayout(Menu03);
        Menu03.setLayout(Menu03Layout);
        Menu03Layout.setHorizontalGroup(
            Menu03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel22)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu03Layout.setVerticalGroup(
            Menu03Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel23)
            .addGroup(Menu03Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22))
        );

        Menu04.setBackground(new java.awt.Color(255, 204, 102));
        Menu04.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu04.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu04MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu04MousePressed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(32, 52, 15));
        jLabel24.setText("Purchase Requition");

        jLabel25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-purchase-for-euro-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu04Layout = new javax.swing.GroupLayout(Menu04);
        Menu04.setLayout(Menu04Layout);
        Menu04Layout.setHorizontalGroup(
            Menu04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu04Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel24)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu04Layout.setVerticalGroup(
            Menu04Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel25)
            .addGroup(Menu04Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel24))
        );

        Menu05.setBackground(new java.awt.Color(255, 204, 102));
        Menu05.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu05.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu05MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu05MousePressed(evt);
            }
        });

        jLabel28.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(32, 52, 15));
        jLabel28.setText(" Purchase Order");

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-purchase-order-30 (1).png"))); // NOI18N

        javax.swing.GroupLayout Menu05Layout = new javax.swing.GroupLayout(Menu05);
        Menu05.setLayout(Menu05Layout);
        Menu05Layout.setHorizontalGroup(
            Menu05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu05Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel29)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel28, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(30, 30, 30))
        );
        Menu05Layout.setVerticalGroup(
            Menu05Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel29)
            .addGroup(Menu05Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel28))
        );

        Menu06.setBackground(new java.awt.Color(255, 204, 102));
        Menu06.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu06.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu06MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu06MousePressed(evt);
            }
        });

        jLabel26.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(32, 52, 15));
        jLabel26.setText("Stock Management");

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-stock-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu06Layout = new javax.swing.GroupLayout(Menu06);
        Menu06.setLayout(Menu06Layout);
        Menu06Layout.setHorizontalGroup(
            Menu06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu06Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel26)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu06Layout.setVerticalGroup(
            Menu06Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel27)
            .addGroup(Menu06Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel26))
        );

        Menu07.setBackground(new java.awt.Color(255, 204, 102));
        Menu07.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu07.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu07MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu07MousePressed(evt);
            }
        });

        jLabel31.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(32, 52, 15));
        jLabel31.setText("Generate Reports");

        jLabel32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-report-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu07Layout = new javax.swing.GroupLayout(Menu07);
        Menu07.setLayout(Menu07Layout);
        Menu07Layout.setHorizontalGroup(
            Menu07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu07Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel32)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel31)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu07Layout.setVerticalGroup(
            Menu07Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32)
            .addGroup(Menu07Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel31))
        );

        Menu08.setBackground(new java.awt.Color(255, 204, 102));
        Menu08.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 1, 2, 1, new java.awt.Color(0, 0, 0)));
        Menu08.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Menu08MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                Menu08MousePressed(evt);
            }
        });

        jLabel33.setFont(new java.awt.Font("Bookman Old Style", 1, 10)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(32, 52, 15));
        jLabel33.setText("Daily Item-Wise Sales");

        jLabel34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-sales-30.png"))); // NOI18N

        javax.swing.GroupLayout Menu08Layout = new javax.swing.GroupLayout(Menu08);
        Menu08.setLayout(Menu08Layout);
        Menu08Layout.setHorizontalGroup(
            Menu08Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Menu08Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel34)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel33)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        Menu08Layout.setVerticalGroup(
            Menu08Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel34)
            .addGroup(Menu08Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel33))
        );

        logoutButton.setBackground(new java.awt.Color(204, 221, 204));
        logoutButton.setFont(new java.awt.Font("Bookman Old Style", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(32, 52, 15));
        logoutButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Icons/icons8-logout-30.png"))); // NOI18N
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(logoutButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(MenuName, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu02, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu03, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu04, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu05, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu06, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu07, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu08, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Menu01, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(MenuName, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(Menu01, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu02, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu03, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu04, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu05, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu06, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu07, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Menu08, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addComponent(logoutButton)
                .addGap(33, 33, 33))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 220, 550));

        jDesktopPanel.setBackground(new java.awt.Color(204, 221, 204));
        jDesktopPanel.setForeground(new java.awt.Color(204, 221, 204));

        jLabel2.setFont(new java.awt.Font("Bookman Old Style", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(32, 52, 15));
        jLabel2.setText("Welcome to Admin Page!");

        jDesktopPanel.setLayer(jLabel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPanelLayout = new javax.swing.GroupLayout(jDesktopPanel);
        jDesktopPanel.setLayout(jDesktopPanelLayout);
        jDesktopPanelLayout.setHorizontalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanelLayout.createSequentialGroup()
                .addGap(160, 160, 160)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 491, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(169, Short.MAX_VALUE))
        );
        jDesktopPanelLayout.setVerticalGroup(
            jDesktopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(411, Short.MAX_VALUE))
        );

        jPanel1.add(jDesktopPanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 0, 820, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1028, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(1028, 550));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void Menu02MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu02MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(ClickedColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Items Management");
    }//GEN-LAST:event_Menu02MousePressed

    private void Menu03MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu03MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(ClickedColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Supplier Management");
    }//GEN-LAST:event_Menu03MousePressed

    private void Menu04MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu04MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(ClickedColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Purchase Requition");
    }//GEN-LAST:event_Menu04MousePressed

    private void Menu05MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu05MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(ClickedColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Purchase Order");
    }//GEN-LAST:event_Menu05MousePressed

    private void Menu06MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu06MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(ClickedColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Stock Management");
    }//GEN-LAST:event_Menu06MousePressed

    private void Menu02MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu02MouseClicked
        // TODO add your handling code here:
        Menu2 menu2=new Menu2();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu2).setVisible(true);
    }//GEN-LAST:event_Menu02MouseClicked

    private void Menu03MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu03MouseClicked
        // TODO add your handling code here:
        Menu3 menu3=new Menu3();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu3).setVisible(true);
    }//GEN-LAST:event_Menu03MouseClicked

    private void Menu04MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu04MouseClicked
        // TODO add your handling code here:
        Menu4 menu4=new Menu4();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu4).setVisible(true);
    }//GEN-LAST:event_Menu04MouseClicked

    private void Menu05MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu05MouseClicked
        // TODO add your handling code here:
        Menu5 menu5=new Menu5();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu5).setVisible(true);
    }//GEN-LAST:event_Menu05MouseClicked

    private void Menu06MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu06MouseClicked
        // TODO add your handling code here:
        Menu6 menu6=new Menu6();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu6).setVisible(true);
    }//GEN-LAST:event_Menu06MouseClicked

    private void Menu01MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu01MouseClicked
        // TODO add your handling code here:
        // Dispose the AdminTest frame
        this.dispose();

        // Open AdminPage as a new JFrame
        AdminPage adminPage = new AdminPage("exampleIdentifier:Position"); // Pass identifier if needed
        adminPage.setVisible(true);
        adminPage.setLocationRelativeTo(null);
        adminPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }//GEN-LAST:event_Menu01MouseClicked

    private void Menu01MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu01MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(ClickedColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Employee Management");
    }//GEN-LAST:event_Menu01MousePressed

    private void Menu07MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu07MouseClicked
        // TODO add your handling code here:
        Menu7 menu7=new Menu7();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu7).setVisible(true);
    }//GEN-LAST:event_Menu07MouseClicked

    private void Menu07MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu07MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(ClickedColor);
        Menu08.setBackground(DefaultColor);
        
        MenuName.setText("Generate Reports");
    }//GEN-LAST:event_Menu07MousePressed

    private void Menu08MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu08MouseClicked
        // TODO add your handling code here:
        Menu8 menu8=new Menu8();
        jDesktopPanel.removeAll();
        jDesktopPanel.add(menu8).setVisible(true);
    }//GEN-LAST:event_Menu08MouseClicked

    private void Menu08MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Menu08MousePressed
        // TODO add your handling code here:
        Menu01.setBackground(DefaultColor); 
        Menu02.setBackground(DefaultColor); 
        Menu03.setBackground(DefaultColor); 
        Menu04.setBackground(DefaultColor); 
        Menu05.setBackground(DefaultColor); 
        Menu06.setBackground(DefaultColor);
        Menu07.setBackground(DefaultColor);
        Menu08.setBackground(ClickedColor);
        
        MenuName.setText("Daily Item-Wise Sales");
    }//GEN-LAST:event_Menu08MousePressed

    
    
    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        int response = JOptionPane.showConfirmDialog(this, 
        "Are you sure you want to log out?", 
        "Logout Confirmation", 
        JOptionPane.YES_NO_OPTION, 
        JOptionPane.QUESTION_MESSAGE);

        // Check the user's response
        if (response == JOptionPane.YES_OPTION) {
            // Dispose the AdminTest frame
            this.dispose();

            // Open Loginpage1 frame
            Loginpage1 loginPage = new Loginpage1();
            loginPage.setVisible(true);
            loginPage.pack();
            loginPage.setLocationRelativeTo(null);
            loginPage.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        }
    }//GEN-LAST:event_logoutButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminTest.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new AdminTest().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu01;
    private javax.swing.JPanel Menu02;
    private javax.swing.JPanel Menu03;
    private javax.swing.JPanel Menu04;
    private javax.swing.JPanel Menu05;
    private javax.swing.JPanel Menu06;
    private javax.swing.JPanel Menu07;
    private javax.swing.JPanel Menu08;
    private javax.swing.JLabel MenuName;
    private javax.swing.JDesktopPane jDesktopPanel;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JButton logoutButton;
    // End of variables declaration//GEN-END:variables
}
